CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260307131638_InitialCreate') THEN
    CREATE TABLE "AspNetRoles" (
        "Id" text NOT NULL,
        "Name" character varying(256),
        "NormalizedName" character varying(256),
        "ConcurrencyStamp" text,
        CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260307131638_InitialCreate') THEN
    CREATE TABLE "AspNetUsers" (
        "Id" text NOT NULL,
        "FirstName" character varying(100) NOT NULL,
        "LastName" character varying(100) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "LastLoginAt" timestamp with time zone,
        "UserName" character varying(256),
        "NormalizedUserName" character varying(256),
        "Email" character varying(256),
        "NormalizedEmail" character varying(256),
        "EmailConfirmed" boolean NOT NULL,
        "PasswordHash" text,
        "SecurityStamp" text,
        "ConcurrencyStamp" text,
        "PhoneNumber" text,
        "PhoneNumberConfirmed" boolean NOT NULL,
        "TwoFactorEnabled" boolean NOT NULL,
        "LockoutEnd" timestamp with time zone,
        "LockoutEnabled" boolean NOT NULL,
        "AccessFailedCount" integer NOT NULL,
        CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260307131638_InitialCreate') THEN
    CREATE TABLE "AspNetRoleClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoleId" text NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260307131638_InitialCreate') THEN
    CREATE TABLE "AspNetUserClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" text NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260307131638_InitialCreate') THEN
    CREATE TABLE "AspNetUserLogins" (
        "LoginProvider" text NOT NULL,
        "ProviderKey" text NOT NULL,
        "ProviderDisplayName" text,
        "UserId" text NOT NULL,
        CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
        CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260307131638_InitialCreate') THEN
    CREATE TABLE "AspNetUserRoles" (
        "UserId" text NOT NULL,
        "RoleId" text NOT NULL,
        CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
        CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260307131638_InitialCreate') THEN
    CREATE TABLE "AspNetUserTokens" (
        "UserId" text NOT NULL,
        "LoginProvider" text NOT NULL,
        "Name" text NOT NULL,
        "Value" text,
        CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
        CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260307131638_InitialCreate') THEN
    CREATE TABLE "CommitmentDevices" (
        "Id" uuid NOT NULL,
        "UserId" text NOT NULL,
        "Name" character varying(200) NOT NULL,
        "Description" character varying(500) NOT NULL,
        "RuleType" text NOT NULL,
        "ThresholdAmount" numeric(18,2),
        "Category" text,
        "ActiveDays" jsonb,
        "ActiveFromHour" integer,
        "ActiveToHour" integer,
        "Action" text NOT NULL,
        "IsActive" boolean NOT NULL,
        "TriggerCount" integer NOT NULL,
        "HeededCount" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_CommitmentDevices" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_CommitmentDevices_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260307131638_InitialCreate') THEN
    CREATE TABLE "SpendingTriggers" (
        "Id" uuid NOT NULL,
        "UserId" text NOT NULL,
        "TriggerType" text NOT NULL,
        "Label" character varying(200) NOT NULL,
        "Insight" character varying(500) NOT NULL,
        "AverageOverspendPercent" numeric(5,2) NOT NULL,
        "Category" text NOT NULL,
        "SampleSize" integer NOT NULL,
        "ConfidenceScore" double precision NOT NULL,
        "DetectedAt" timestamp with time zone NOT NULL,
        "LastUpdatedAt" timestamp with time zone NOT NULL,
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_SpendingTriggers" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_SpendingTriggers_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260307131638_InitialCreate') THEN
    CREATE TABLE "Transactions" (
        "Id" uuid NOT NULL,
        "UserId" text NOT NULL,
        "Amount" numeric(18,2) NOT NULL,
        "Currency" character varying(3) NOT NULL DEFAULT 'USD',
        "Description" character varying(500) NOT NULL,
        "Category" character varying(100) NOT NULL,
        "Merchant" character varying(200),
        "TransactionDate" timestamp with time zone NOT NULL,
        "LocationLatitude" text,
        "LocationLongitude" text,
        "LocationLabel" text,
        "EmotionalState" text,
        "EmotionalNote" text,
        "IsImpulse" boolean NOT NULL,
        "NudgeShown" boolean NOT NULL,
        "NudgeHeeded" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Transactions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Transactions_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260307131638_InitialCreate') THEN
    CREATE TABLE "TriggerTransactions" (
        "SpendingTriggerId" uuid NOT NULL,
        "TransactionId" uuid NOT NULL,
        CONSTRAINT "PK_TriggerTransactions" PRIMARY KEY ("SpendingTriggerId", "TransactionId"),
        CONSTRAINT "FK_TriggerTransactions_SpendingTriggers_SpendingTriggerId" FOREIGN KEY ("SpendingTriggerId") REFERENCES "SpendingTriggers" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_TriggerTransactions_Transactions_TransactionId" FOREIGN KEY ("TransactionId") REFERENCES "Transactions" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260307131638_InitialCreate') THEN
    CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260307131638_InitialCreate') THEN
    CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260307131638_InitialCreate') THEN
    CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260307131638_InitialCreate') THEN
    CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260307131638_InitialCreate') THEN
    CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260307131638_InitialCreate') THEN
    CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260307131638_InitialCreate') THEN
    CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260307131638_InitialCreate') THEN
    CREATE INDEX "IX_CommitmentDevices_UserId" ON "CommitmentDevices" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260307131638_InitialCreate') THEN
    CREATE INDEX "IX_SpendingTriggers_UserId" ON "SpendingTriggers" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260307131638_InitialCreate') THEN
    CREATE INDEX "IX_Transactions_TransactionDate" ON "Transactions" ("TransactionDate");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260307131638_InitialCreate') THEN
    CREATE INDEX "IX_Transactions_UserId" ON "Transactions" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260307131638_InitialCreate') THEN
    CREATE INDEX "IX_Transactions_UserId_Category" ON "Transactions" ("UserId", "Category");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260307131638_InitialCreate') THEN
    CREATE INDEX "IX_TriggerTransactions_TransactionId" ON "TriggerTransactions" ("TransactionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260307131638_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260307131638_InitialCreate', '8.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630064517_AddMerchantKeywordDropTriggerTransaction') THEN
    DROP TABLE "TriggerTransactions";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630064517_AddMerchantKeywordDropTriggerTransaction') THEN
    ALTER TABLE "CommitmentDevices" ALTER COLUMN "Category" TYPE character varying(100);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630064517_AddMerchantKeywordDropTriggerTransaction') THEN
    ALTER TABLE "CommitmentDevices" ADD "MerchantKeyword" character varying(200);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630064517_AddMerchantKeywordDropTriggerTransaction') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260630064517_AddMerchantKeywordDropTriggerTransaction', '8.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630074947_AddIncomeTypeAndBudgets') THEN
    ALTER TABLE "Transactions" ADD "Type" character varying(20) NOT NULL DEFAULT 'Expense';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630074947_AddIncomeTypeAndBudgets') THEN
    CREATE TABLE "Budgets" (
        "Id" uuid NOT NULL,
        "UserId" text NOT NULL,
        "Year" integer NOT NULL,
        "Month" integer NOT NULL,
        "OverallLimit" numeric(18,2),
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Budgets" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Budgets_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630074947_AddIncomeTypeAndBudgets') THEN
    CREATE TABLE "BudgetCategories" (
        "Id" uuid NOT NULL,
        "BudgetId" uuid NOT NULL,
        "Category" character varying(100) NOT NULL,
        "Limit" numeric(18,2) NOT NULL,
        CONSTRAINT "PK_BudgetCategories" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_BudgetCategories_Budgets_BudgetId" FOREIGN KEY ("BudgetId") REFERENCES "Budgets" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630074947_AddIncomeTypeAndBudgets') THEN
    CREATE UNIQUE INDEX "IX_BudgetCategories_BudgetId_Category" ON "BudgetCategories" ("BudgetId", "Category");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630074947_AddIncomeTypeAndBudgets') THEN
    CREATE UNIQUE INDEX "IX_Budgets_UserId_Year_Month" ON "Budgets" ("UserId", "Year", "Month");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630074947_AddIncomeTypeAndBudgets') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260630074947_AddIncomeTypeAndBudgets', '8.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630084441_AddSavingsBillsDebts') THEN
    CREATE TABLE "Bills" (
        "Id" uuid NOT NULL,
        "UserId" text NOT NULL,
        "Name" character varying(200) NOT NULL,
        "Amount" numeric(18,2) NOT NULL,
        "Category" character varying(100) NOT NULL,
        "NextDueDate" timestamp with time zone NOT NULL,
        "Recurrence" character varying(20) NOT NULL,
        "ReminderDaysBefore" integer NOT NULL,
        "IsActive" boolean NOT NULL,
        "LastPaidDate" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Bills" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Bills_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630084441_AddSavingsBillsDebts') THEN
    CREATE TABLE "Debts" (
        "Id" uuid NOT NULL,
        "UserId" text NOT NULL,
        "Name" character varying(200) NOT NULL,
        "DebtType" character varying(30) NOT NULL,
        "OriginalBalance" numeric(18,2) NOT NULL,
        "CurrentBalance" numeric(18,2) NOT NULL,
        "InterestRate" numeric(5,2) NOT NULL,
        "MinimumPayment" numeric(18,2) NOT NULL,
        "DueDayOfMonth" integer,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Debts" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Debts_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630084441_AddSavingsBillsDebts') THEN
    CREATE TABLE "SavingsGoals" (
        "Id" uuid NOT NULL,
        "UserId" text NOT NULL,
        "Name" character varying(200) NOT NULL,
        "Notes" character varying(500),
        "TargetAmount" numeric(18,2) NOT NULL,
        "Deadline" timestamp with time zone,
        "Priority" character varying(20) NOT NULL,
        "IsCompleted" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_SavingsGoals" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_SavingsGoals_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630084441_AddSavingsBillsDebts') THEN
    CREATE TABLE "DebtPayments" (
        "Id" uuid NOT NULL,
        "DebtId" uuid NOT NULL,
        "Amount" numeric(18,2) NOT NULL,
        "Date" timestamp with time zone NOT NULL,
        "Note" character varying(300),
        CONSTRAINT "PK_DebtPayments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_DebtPayments_Debts_DebtId" FOREIGN KEY ("DebtId") REFERENCES "Debts" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630084441_AddSavingsBillsDebts') THEN
    CREATE TABLE "SavingsContributions" (
        "Id" uuid NOT NULL,
        "SavingsGoalId" uuid NOT NULL,
        "Amount" numeric(18,2) NOT NULL,
        "Date" timestamp with time zone NOT NULL,
        "Note" character varying(300),
        CONSTRAINT "PK_SavingsContributions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_SavingsContributions_SavingsGoals_SavingsGoalId" FOREIGN KEY ("SavingsGoalId") REFERENCES "SavingsGoals" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630084441_AddSavingsBillsDebts') THEN
    CREATE INDEX "IX_Bills_UserId_NextDueDate" ON "Bills" ("UserId", "NextDueDate");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630084441_AddSavingsBillsDebts') THEN
    CREATE INDEX "IX_DebtPayments_DebtId" ON "DebtPayments" ("DebtId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630084441_AddSavingsBillsDebts') THEN
    CREATE INDEX "IX_Debts_UserId" ON "Debts" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630084441_AddSavingsBillsDebts') THEN
    CREATE INDEX "IX_SavingsContributions_SavingsGoalId" ON "SavingsContributions" ("SavingsGoalId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630084441_AddSavingsBillsDebts') THEN
    CREATE INDEX "IX_SavingsGoals_UserId" ON "SavingsGoals" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630084441_AddSavingsBillsDebts') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260630084441_AddSavingsBillsDebts', '8.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630091924_AddAccounts') THEN
    ALTER TABLE "Transactions" ADD "AccountId" uuid;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630091924_AddAccounts') THEN
    CREATE TABLE "Accounts" (
        "Id" uuid NOT NULL,
        "UserId" text NOT NULL,
        "Name" character varying(200) NOT NULL,
        "AccountType" character varying(30) NOT NULL,
        "StartingBalance" numeric(18,2) NOT NULL,
        "IsArchived" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Accounts" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Accounts_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630091924_AddAccounts') THEN
    CREATE TABLE "AccountTransfers" (
        "Id" uuid NOT NULL,
        "UserId" text NOT NULL,
        "FromAccountId" uuid NOT NULL,
        "ToAccountId" uuid NOT NULL,
        "Amount" numeric(18,2) NOT NULL,
        "Date" timestamp with time zone NOT NULL,
        "Note" character varying(300),
        CONSTRAINT "PK_AccountTransfers" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AccountTransfers_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630091924_AddAccounts') THEN
    CREATE INDEX "IX_Transactions_AccountId" ON "Transactions" ("AccountId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630091924_AddAccounts') THEN
    CREATE INDEX "IX_Accounts_UserId" ON "Accounts" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630091924_AddAccounts') THEN
    CREATE INDEX "IX_AccountTransfers_UserId" ON "AccountTransfers" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630091924_AddAccounts') THEN
    ALTER TABLE "Transactions" ADD CONSTRAINT "FK_Transactions_Accounts_AccountId" FOREIGN KEY ("AccountId") REFERENCES "Accounts" ("Id") ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630091924_AddAccounts') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260630091924_AddAccounts', '8.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630092716_AddAuditLog') THEN
    CREATE TABLE "AuditLogs" (
        "Id" uuid NOT NULL,
        "UserId" text,
        "UserEmail" character varying(256),
        "Action" character varying(100) NOT NULL,
        "Details" character varying(1000),
        "Timestamp" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_AuditLogs" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630092716_AddAuditLog') THEN
    CREATE INDEX "IX_AuditLogs_Timestamp" ON "AuditLogs" ("Timestamp");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630092716_AddAuditLog') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260630092716_AddAuditLog', '8.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630094054_AddSharedBudgets') THEN
    CREATE TABLE "SharedBudgets" (
        "Id" uuid NOT NULL,
        "OwnerId" text NOT NULL,
        "Name" character varying(200) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_SharedBudgets" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630094054_AddSharedBudgets') THEN
    CREATE TABLE "SharedBudgetMembers" (
        "Id" uuid NOT NULL,
        "SharedBudgetId" uuid NOT NULL,
        "UserId" text,
        "InvitedEmail" character varying(256) NOT NULL,
        "Role" character varying(20) NOT NULL,
        "Status" character varying(20) NOT NULL,
        "InvitedAt" timestamp with time zone NOT NULL,
        "JoinedAt" timestamp with time zone,
        CONSTRAINT "PK_SharedBudgetMembers" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_SharedBudgetMembers_SharedBudgets_SharedBudgetId" FOREIGN KEY ("SharedBudgetId") REFERENCES "SharedBudgets" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630094054_AddSharedBudgets') THEN
    CREATE TABLE "SharedExpenses" (
        "Id" uuid NOT NULL,
        "SharedBudgetId" uuid NOT NULL,
        "PaidByUserId" text NOT NULL,
        "Description" character varying(300) NOT NULL,
        "Category" character varying(100) NOT NULL,
        "Amount" numeric(18,2) NOT NULL,
        "Date" timestamp with time zone NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_SharedExpenses" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_SharedExpenses_SharedBudgets_SharedBudgetId" FOREIGN KEY ("SharedBudgetId") REFERENCES "SharedBudgets" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630094054_AddSharedBudgets') THEN
    CREATE TABLE "SharedExpenseShares" (
        "Id" uuid NOT NULL,
        "SharedExpenseId" uuid NOT NULL,
        "UserId" text NOT NULL,
        "Amount" numeric(18,2) NOT NULL,
        CONSTRAINT "PK_SharedExpenseShares" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_SharedExpenseShares_SharedExpenses_SharedExpenseId" FOREIGN KEY ("SharedExpenseId") REFERENCES "SharedExpenses" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630094054_AddSharedBudgets') THEN
    CREATE INDEX "IX_SharedBudgetMembers_InvitedEmail" ON "SharedBudgetMembers" ("InvitedEmail");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630094054_AddSharedBudgets') THEN
    CREATE UNIQUE INDEX "IX_SharedBudgetMembers_SharedBudgetId_InvitedEmail" ON "SharedBudgetMembers" ("SharedBudgetId", "InvitedEmail");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630094054_AddSharedBudgets') THEN
    CREATE INDEX "IX_SharedBudgetMembers_UserId" ON "SharedBudgetMembers" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630094054_AddSharedBudgets') THEN
    CREATE INDEX "IX_SharedBudgets_OwnerId" ON "SharedBudgets" ("OwnerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630094054_AddSharedBudgets') THEN
    CREATE INDEX "IX_SharedExpenses_SharedBudgetId" ON "SharedExpenses" ("SharedBudgetId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630094054_AddSharedBudgets') THEN
    CREATE INDEX "IX_SharedExpenseShares_SharedExpenseId" ON "SharedExpenseShares" ("SharedExpenseId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630094054_AddSharedBudgets') THEN
    CREATE INDEX "IX_SharedExpenseShares_UserId" ON "SharedExpenseShares" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630094054_AddSharedBudgets') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260630094054_AddSharedBudgets', '8.0.10');
    END IF;
END $EF$;
COMMIT;

